id: hello-world
version: 1.0
type: application
dependencies:
  - id: am-lang-core
    realm: github
    type: git-repo
    tag: latest
    url: https://github.com/anderskjeldsen/am-lang-core.git
platforms:
  - id: libc
    abstract: true
  - id: amigaos
    extends: libc
    gccCommand: m68k-amigaos-gcc
    asmCommand: vasmm68k_mot
    gccAdditionalLibraries:
    additionalHeaders:
    additionalAsmSources:
    additionalCSources:
    additionalIncludePaths:
    gccAdditionalOptions:
       - -noixemul     
    gccLibraryPaths:
  - id: linux-x64
    extends: libc
    gccCommand: gcc

buildTargets:
  - id: amigaos_docker
    platform: amigaos
    dockerBuild:
      image: amiga-gcc
      buildPath: /host
  - id: linux-x64
    platform: linux-x64