id: file-browser
version: 1.0
type: application
dependencies:
  - id: am-lang-core
    realm: github
    type: git-repo
    tag: latest
    url: https://github.com/anderskjeldsen/am-lang-core.git
  - id: am-ui
    realm: github
    type: git-repo
    tag: latest
    url: https://github.com/anderskjeldsen/am-ui.git
platforms:
  - id: libc
    abstract: true
  - id: amigaos
    extends: libc
    gccCommand: m68k-amigaos-gcc
    asmCommand: vasmm68k_mot
    gccAdditionalLibraries:
     - socket
    additionalHeaders:
    additionalAsmSources:
    additionalCSources:
    additionalIncludePaths:
    gccAdditionalOptions:
       - -noixemul     
    gccLibraryPaths:

buildTargets:
  - id: amigaos_docker
    platform: amigaos
    dockerBuild:
      image: amiga-gcc
      buildPath: /host
