# Based on https://github.com/sebastianbergmann/container-amiga-gcc
FROM amiga-gcc-base

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y \
    xz-utils

RUN cd /root/amiga-gcc && \
    make zlib && \
    make libpng

RUN cd / && \
    rm -rf /root/amiga-gcc && \
    apt-get purge -y \
    autoconf \
    bison \
    flex \
    g++ \
    gcc \
    gettext \
    git \
    lhasa \
    libgmp-dev \
    libmpfr-dev \
    libmpc-dev \
    libncurses-dev \
    rsync \
    texinfo\
    wget \
    && apt-get -y autoremove
